sensor:
  - platform: copy
    source_id: ${ats_control_voltage_id}
    id: ${ats_control_name}
    on_value:
       - if:  ##### si tension cellule mini batterie < seuil bas    ######
            condition:
              and:
                - switch.is_on: ${ats_control_id}
            then:
             - if:
                  condition:
                      or:    
                       - lambda: return id(${ats_control_voltage_min_cell_1_id}).state < id(ats_voltage_min_cell_solar_to_grid_number).state;
                       - lambda: return id(${ats_control_voltage_min_cell_2_id}).state < id(ats_voltage_min_cell_solar_to_grid_number).state;
                       - switch.is_on: manu_edf
                  then:
                    - script.execute: script_mode_EDF
 
       - if:  ##### si tension cellule mini batterie < seuil bas    ######
            condition:
              and:
                - switch.is_on: ${ats_control_id}
            then:
             - if:
                  condition:
                      and:    
                       - lambda: return id(${ats_control_voltage_min_cell_1_id}).state > id(ats_voltage_min_cell_grid_to_solar_number).state;
                       - lambda: return id(${ats_control_voltage_min_cell_2_id}).state > id(ats_voltage_min_cell_grid_to_solar_number).state;
                       - switch.is_on: manu_batterie
                  then:          
                    - script.execute: script_mode_batterie
            
script:
  - id: script_mode_EDF
    then:
      - switch.turn_off: ${ats_control_id}             
      - delay: 10s             
      - switch.turn_on: ${ats_control_relay_inverter_id} 
      - delay: 10s
      - select.set: 
            id: ${ats_control_inverteur_mode}
            option: "Solar Utility Battery"
            
  - id: script_mode_batterie
    then:       
            - select.set:
                id: ${ats_control_inverteur_mode} 
                option: "Solar Battery Utility"
            - delay: 10s
            - switch.turn_off: ${ats_control_relay_inverter_id} 
            - switch.turn_on: ${ats_control_id}      